name: Scrape Data

on:
  schedule:
    - cron: '0 0 * * *'  # Thực hiện mỗi ngày lúc nửa đêm
  workflow_dispatch:  # Cho phép kích hoạt thủ công

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Chọn phiên bản Python bạn cần

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        
    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser
    # - name: Install Edge and EdgeDriver
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y wget software-properties-common
    #     wget https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
    #     sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    #     sudo apt-get update
    #     sudo apt-get install -y microsoft-edge-stable
    #     EDGE_VERSION=$(microsoft-edge --version | grep -oP '\d+\.\d+\.\d+\.\d+')
    #     wget https://msedgedriver.azureedge.net/${EDGE_VERSION}/edgedriver_linux64.zip
    #     unzip edgedriver_linux64.zip
    #     sudo mv msedgedriver /usr/local/bin/

    - name: Run scraping script
      run: python scrape_data.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update scraped data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
